### ISSUE TITLE
[Warlock] - Unstable Affliction

### ISSUE THREAD

**Issue by Jildor** [tobmaps/TrinityCore#10]
Spell:  http://old.wowhead.com/spell=30108
Periodic damage works well with the resilience, but the debuff to dispell, cause the same damage with or without resilience.

thx

**Comment by tobmaps** [comment]
try this https://gist.github.com/921419 and let me know if it works (i hope works)

**Comment by Jildor** [comment]
I think still bug :S

**Comment by tobmaps** [comment]
very bad :( need to do more research but i don't want to do it now

**Comment by tobmaps** [comment]
fixed in [p165]
