### ISSUE TITLE
[Друид/Талант] Бешенство совуха

### ISSUE THREAD

**Issue by Ramusik** [tobmaps/TrinityCore#105]
http://ru.wowhead.com/spell=48389

Должен прокать от любого получения урона - согласно http://www.wowwiki.com/Owlkin_Frenzy#cite_note-0

Owlkin Frenzy still procs off of any damage type, including spell/AoE

Фикс (автор - я):
http://paste2.org/p/1409674

**Comment by Ramusik** [comment]
Тут то же самое ....

**Comment by tobmaps** [comment]
не баг, а там указано "closes 105", в TC свои иссуи со своей нумерацией
