### ISSUE TITLE
Bloodlust / Heroism

### ISSUE THREAD

**Issue by Wattiqelumes** [tobmaps/TrinityCore#107]
Should go through Line of Sight, right now you only get the buff if your party member(s) is/are in LoS.

Videoproof at 5:11
http://warcraftmovies.com/movieview.php?id=154817

**Comment by tobmaps** [comment]
seems we need to apply this http://getmangos.com/community/post/134605/#p134605 but need more test
Ofc this is not a fix for your bug, but this is from same category

**Comment by Wattiqelumes** [comment]
Same counts for Hymn of Hope/Divine. ;)

**Comment by ghost** [comment]
another bug for, if you use this spells in 1. arena, you have "sated" in the next arena too, it must be removed after join to the new arena

**Comment by Wattiqelumes** [comment]
@telsamat: Tobmaps once made a patch for that. ;)

**Comment by ghost** [comment]
ok np :-) i saw this ability report so i reported another important bugs :)

**Comment by tobmaps** [comment]
hm, one random idea about problem with Sated... http://paste2.org/p/1453064

**Comment by ghost** [comment]
can you add it to the repo?

**Comment by tobmaps** [comment]
need at least some tests to be sure if it doesn't break something, anyway I'm closing this Issue since it fixed in my repo
