### ISSUE TITLE
Mana Shield

### ISSUE THREAD

**Issue by Wattiqelumes** [tobmaps/TrinityCore#108]
Drains way too much mana. I believe 1.5x instead of 2x.

I can test more throughly if you want me to.

**Comment by tobmaps** [comment]
```
I can test more throughly if you want me to.
```

ofc you should test it as much as you can

**Comment by Wattiqelumes** [comment]
Just reported so I wouldn't forget. Will update later on.

Also, turns out I was wrong. It ABROSB too much, hence it drains too much as well. Will give correct and wrong values soon.

**Comment by Wattiqelumes** [comment]
Ugh. I was wrong. It works perfectly Blizzlike, didn't realize it should (and does) scale with spell power.

**Comment by tobmaps** [comment]
then closed
