### ISSUE TITLE
[Warrior] Glyph of Command/Battle + Booming Voice

### ISSUE THREAD

**Issue by Jildor** [tobmaps/TrinityCore#109]
- Glyph of Battle: Increases the duration of your Battle Shout ability by 2 min.
- Glyph of Command: Increases the duration of your Commanding Shout ability by 2 min.
- Booming Voice: Increases the area of effect and duration of your Battle Shout, Demoralizing Shout and Commanding Shout by 50%.

I Have the Following question:
The talent is added to the glyph or just skill?
That is, Should take 5 minutes or 6 minutes?

In spell put 6minutes but duration is 5minutes.

Thx

**Comment by tobmaps** [comment]
because timer starts to count from 5:59

**Comment by Jildor** [comment]
reaches 5 minutes, but the description makes 6.

So is the error description or duration?

Thx.

**Comment by tobmaps** [comment]
think there is no error at all

**Comment by Jildor** [comment]
So why spell count start in 4:59 and spell description put 6minutes?
Sorry but I don't understand

**Comment by tobmaps** [comment]
oh, now understand. Need to check

**Comment by codels** [comment]
seconds are not displayed if left > minutes
5:59, 59 sec not displayed... 5:01 and  5:59 displayed 5 minutes, total 6 minutes

**Comment by Jildor** [comment]
But start in less than 5 minutes :S

**Comment by codels** [comment]
if start on 5 minutes, displayd 4minutes (59 second not show)
if start on 1 minutes, displayed 59 seconds
if start on 2 minutes, displayed 1 minutes (59 second not show)

**Comment by Jildor** [comment]
But this: http://i707.photobucket.com/albums/ww73/10100110003/WoWScrnShot_051111_142404.jpg

See image, 5min buff duration and spell description 6minutes.

**Comment by tobmaps** [comment]
oh, that is what i said at my first comment. So it's isn't a bug at all. You are hopefully confused me and self %)

**Comment by Jildor** [comment]
FFFFUUUU T.T
http://oi56.tinypic.com/25s5tev.jpg
See this image, blue bar.

I cast Battle Shout with Glyph of Battle and Booming Voice, but count is 4:59.
in spell description put 6 minutes....please go to game and check...T.T

thx.

**Comment by tobmaps** [comment]
your duration bar addon works wrong :S

**Comment by Jildor** [comment]
Sorry for reopen....but...

WTF!

Please, take a stopwatch and test...
4:59 minutes....

**Comment by tobmaps** [comment]
works fine for me, just tested. Used - it shows 5 min in buff, waited, seeing at my clocks - after 6 mins it removed from me
any questions?
