### ISSUE TITLE
[Paladin] Retribution aura

### ISSUE THREAD

**Issue by 3kids** [tobmaps/TrinityCore#11]
- What steps will reproduce the problem?
  1.Have paladin
  2.Activate ret aura (we do the test with its improval ->sanctified retribution->50%increaed dmg+3%bonus to holy dmg)
  3.Take damage (melee)
- What is the expected output?
  So ret aura dmg should be-> affected <-by this talent by 50% (and it is! but...). Current dmg becomes 168dmg(the damage is just 50% higher from its base witout any bonus to holy dmg affection). But this talent has 3% more damage and +crusade(6%)=9% increased holy dmg. 168x9%=15.12dmg -> 168+15~=183dmg. This is the damage ret aura should do if having sanctified retribution+crusade. Also vengeance should also affect the aura and with 3x stacks its another 9% bonus to holy damage. Which all means 168x18%=30.24dmg. So if you have those talents and 3x stacks of vengeance your aura should do-> 168+30~=198 modified dmg.
- What do you see instead?
  I see always same amount of 168dmg. Not affected by any adds to holy dmg and it should.

**Comment by tobmaps** [comment]
your aren't installed [p60]. Closed
Make sure that you installed all of patches or even whole branch before post any Issues to the tracker

**Comment by 3kids** [comment]
I have setup a clean repo only with your patches and it still does not work :s

**Comment by Veretos** [comment]
Did you run the SQL files located in sql/custom folder?

**Comment by 3kids** [comment]
Ye

**Comment by tobmaps** [comment]
you tried to use my core or just several patches from him?

**Comment by 3kids** [comment]
Tried both, didn't work

**Comment by tobmaps** [comment]
oh, i'm starting to understand what are you mean xD 
And now i see the problem... Retribution Aura really doesn't get any PCT bonuses from talents
Same thing with druid's Thorns

**Comment by 3kids** [comment]
Ye thats what i meant :>

**Comment by tobmaps** [comment]
fixed in [p134]. But fixed only for case of SPELL_AURA_MOD_DAMAGE_PERCENT_DONE
Also added spell damage bonus for it

**Comment by 3kids** [comment]
Awesome, ty

**Comment by tobmaps** [comment]
i will re-add this patch with proper implementation of all cases. I have an idea ^^

EDIT:

re-added. Now their damage also will be modified by auras that increase/decrease damage taken
