### ISSUE TITLE
Judgement and Seal of Righteousness interraction

### ISSUE THREAD

**Issue by Craghorn** [tobmaps/TrinityCore#113]
Seal of Righteousness should do it's seal damage after Judgement's.
id's if it helps.
Judgement of Light 20271
of Justice 53407
of Wisdom 53408
Spell id of Judgement of Righteousness dmg 20187
Spell id of Seal of Righteousness 25742

**Comment by Craghorn** [comment]
http://www.trinitycore.org/t/trinitycore/ticket/372
This issue

**Comment by Craghorn** [comment]
http://www.wowwiki.com/Seal_of_Righteousness
And official too)

**Comment by tobmaps** [comment]
don't click Comment & Close button :/

**Comment by Craghorn** [comment]
Yep, something automatic))

**Comment by Craghorn** [comment]
Something wrong with spell 20187, i think.
If add melee class, seal would proc from it.

**Comment by tobmaps** [comment]
```
melee class
```

you mean procFlag for melee spells?

**Comment by Craghorn** [comment]
Yep. I think that Spell 20187 somewhat have non-melee class.
And cuz that don't proc Seal.
Or mb problem depeer than i think.

**Comment by tobmaps** [comment]
Fixed in official repo
