### ISSUE TITLE
[rogue] Distract spell (Отвлечение)

### ISSUE THREAD

**Issue by cooler1986** [tobmaps/TrinityCore#114]
Да тут проблема похлеще есть - у Разбойников один из основных спеллов  - Отвлечение (Distract) [URL="http://www.wowhead.com/spell=1725"]http://www.wowhead.com/spell=1725[/URL] не работает как надо. Мобы просто останавливаются и всё - а должны поворачиваться в сторону  на 10 секунд куда была брошена шашка. 4 месяца issue висит на TrinityCore [URL="http://www.trinitycore.org/t/trinitycore/ticket/112"]http://www.trinitycore.org/t/trinitycore/ticket/112[/URL] как я понял [B]tobmaps[/B] не плохо разбирается в спеллах - большая просьба почините пожалуйста этот спелл,люблю играть за Разбойника, но вот  тока это расстраивает. :not_i: Вот код спела Distract с TrinityCore:

void Spell::EffectPull(SpellEffIndex effIndex)
{
    // TODO: create a proper pull towards distract spell center for distract
    EffectNULL(effIndex);
}

void Spell::EffectDistract(SpellEffIndex /_effIndex_/)
{
    // Check for possible target
    if (!unitTarget || unitTarget->isInCombat())
        return;

```
// target must be OK to do this
if (unitTarget->hasUnitState(UNIT_STAT_CONFUSED | UNIT_STAT_STUNNED | UNIT_STAT_FLEEING))
    return;

float angle = unitTarget->GetAngle(&m_targets.m_dstPos);

if (unitTarget->GetTypeId() == TYPEID_PLAYER)
{
    // For players just turn them
    unitTarget->ToPlayer()->SetPosition(unitTarget->GetPositionX(), unitTarget->GetPositionY(), unitTarget->GetPositionZ(), angle, false);
    unitTarget->ToPlayer()->SendTeleportAckPacket();
}
else
{
    // Set creature Distracted, Stop it, And turn it
    unitTarget->SetOrientation(angle);
    unitTarget->StopMoving();
    unitTarget->GetMotionMaster()->MoveDistract(damage * IN_MILLISECONDS);
}
```

}

**Comment by tobmaps** [comment]
прям с тегами от форума :)

**Comment by cooler1986** [comment]
виноват ))))

**Comment by tobmaps** [comment]
а зачем закрыли?

**Comment by cooler1986** [comment]
по ошибке нажал на кнопку)))
