### ISSUE TITLE
Druid 2T 10 (Balance)

### ISSUE THREAD

**Issue by drey113** [tobmaps/TrinityCore#116]
Moonkin 2T10p bonus not working

How it should work: When you gain Clearcasting from your Omen of Clarity talent, you deal 15% additional Nature and Arcane damage for 6 sec.

How it works now: U get clearcasting, but u don't get buff called Omen of Doom (http://www.wowhead.com/spell=70721 )

How to reproduce the problem: Best way is go to orgrimmar where are 2-4 dummie near one by one and use Hurricane on them, more targets, the higher possibility to get clearcasting. Or just spam wrath on dummies.

**Comment by tobmaps** [comment]
http://www.trinitycore.org/t/trinitycore/ticket/484 
it just for me to know what to close :)

**Comment by Ramusik** [comment]
not only - http://www.trinitycore.org/t/trinitycore/ticket/768, http://www.trinitycore.org/t/trinitycore/ticket/261

**Comment by Ramusik** [comment]
Кстати, мой фикс работает идеально, и не требует изменений в ядре, жалко что его признали "хаковым"

**Comment by tobmaps** [comment]
Да потому что оно не должно через spell_linked_spel делаться и ограничиваться через conditions. Нужно в ядре скриптить, желательно в spell_druid.cpp

**Comment by SignFinder** [comment]
<Кстати, мой фикс работает идеально, и не требует изменений в ядре, жалко что его признали "хаковым"
где взять?

**Comment by tobmaps** [comment]
Фикс от Cyberbrest лучше, скоро будет в оффрепо
Will be fixed in off-repo soon

**Comment by drey113** [comment]
да ты просто бог ^_^
