### ISSUE TITLE
[DK]Blood-caked blade

### ISSUE THREAD

**Issue by lendan** [tobmaps/TrinityCore#117]
http://www.wowhead.com/spell=49628/blood-caked-blade

Works almost ok,it procs but it doesnt add +12.5% dmg per disease
http://www.trinitycore.org/t/trinitycore/ticket/1003

**Comment by lendan** [comment]
Did i make some kind of misstake while reporting issue or you're just busy with more important stuff right now ?:)

**Comment by tobmaps** [comment]
Can't reproduce this problem. It works fine for me at c4a0d47e0eef8440ee18f4abd9b02028425928cf

**Comment by lendan** [comment]
To reproduce this problem u should make shadowfrost death knight with bcb talent,and dps dummy for couple of mins then check ur recount numbers,in patch 3.3.5a BCB should deal around 5% of SFdk dps and right now it deals around 0.5 to top 0,7% which makes me think that it still doesn't add +12.5% dmg per disease :p
I've got connection problems with my server right now,my provider doin some maintance i suppose,when its up again i'll post some recount numbers and screenshots

EDIT: Whoops,didnt mean to close:p

EDIT2: You were right,i did check this talent few mins ago and the dmg it deals and it works just fine already,thank you :)
