### ISSUE TITLE
Hysteria

### ISSUE THREAD

**Issue by Wattiqelumes** [tobmaps/TrinityCore#119]
Breaks crows control effects like Blind.

**Comment by tobmaps** [comment]
why shouldn't? Give a link to the source

**Comment by Wattiqelumes** [comment]
http://www.wowwiki.com/Hysteria
http://www.wowhead.com/spell=55975

There's just in no possible way anything related to Hysteria breaks CC.

**Comment by tobmaps** [comment]
hmm

```
 Patch 3.1.0 (2009-04-14): This ability now causes the target to lose health rather than take damage.
```

maybe because of this it shouldn't break

**Comment by Wattiqelumes** [comment]
I apologize, my friend told me wrong.
When a DK activates Hysteria, he should lose 1% HP every second, but instead it DAMAGES for 1 HP, breaking all CC (sheep, blind, etc.) on the DK.

**Comment by tobmaps** [comment]
fixed in official repo
