### ISSUE TITLE
[Shaman] Feral Spirit

### ISSUE THREAD

**Issue by 3kids** [tobmaps/TrinityCore#12]
How to reproduce:
1. Learn Feral spirit
2. Place yourself like 30 meters away from a dummy
3. call feral spirits and deactivate autocast on "Spirit wolf leap"
4. Send the pets to attack the dummy

What is the expected output:
Spirit wolfs should not leap.

What do you see instead:

Spirit wolfs leap to yourself even though autocast is deactivated.

**Comment by tobmaps** [comment]
i can confirm but i need more info about "how it should work". I need to know in what cases it should jump to enemy or even to friend

**Comment by 3kids** [comment]
I found out that the main issue is basically here:

void CharmInfo::ToggleCreatureAutocast(uint32 spellid, bool apply)
{
    if (IsPassiveSpell(spellid))
    {
        sLog->outString("PassiveSpell");
        return;
    }

```
if (apply)
    sLog->outString("TOTALY APPLY");
else
    sLog->outString("Doesnt apply");

for (uint32 x = 0; x < MAX_SPELL_CHARM; ++x)
    if (spellid == m_charmspells[x].GetAction())
    {
        sLog->outString("Spellid %u",spellid);
        m_charmspells[x].SetType(apply ? ACT_ENABLED : ACT_DISABLED);
    }
```

}

I have set up some debug messages and it seems like for leap its always ACT_ENABLED because when i replace it with ACT_DISABLED it doesnt autocast anymore, maybe this helps

**Comment by 3kids** [comment]
Okay i got the problem now IOO%, the disabled gets only set for 1 spirit wolf but it should get for both, so one always still autocasts

**Comment by tobmaps** [comment]
problem somewhere in PetHandler.cpp, maybe in

```
void WorldSession::HandlePetSetAction(WorldPacket & recv_data)
```

**Comment by tobmaps** [comment]
maybe something like this would help http://paste2.org/p/1397038 - added in [p163]

but this can make both wolves to use stun at one time

EDITED:

okay, bug with Bash already exist even without this patch.

Pet system is so horrible... has so horrible implementation ^^

**Comment by 2010phenix** [comment]
maybe time to put half by half your works in pet repo?

**Comment by tobmaps** [comment]
pet branch contains only fixes for pet stat system and i don't want to add any not related to this fixes, anyway pet branch has enough bugs and i just don't want to add more xD

fixed second bug (with Bash) in [p164]

**Comment by 2010phenix** [comment]
+1
thx)

**Comment by tobmaps** [comment]
Anyway this bug is fixed in official repo, the only problem left with Bash, but it fixed by hack-patch [p164]

**Comment by 2010phenix** [comment]
lol
QAston have kittens that community find another spell guru and come to light from laziness ))
