### ISSUE TITLE
Cobra Strikes

### ISSUE THREAD

**Issue by SignFinder** [tobmaps/TrinityCore#121]
off ticket
http://www.trinitycore.org/t/trinitycore/ticket/710

http://old.wowhead.com/spell=53260 - С вероятностью 60% после нанесения вами критического урона способностями "Чародейский выстрел", "Верный выстрел" или "Убийственный выстрел" 2 следующие особые способности вашего питомца также нанесут критический урон.

После использования 2х особых способностей питомца, баф не пропадает, стаки не расходуются.

**Comment by tobmaps** [comment]
У меня это исправлено и давно. Правда грубым хаком [p23]
