### ISSUE TITLE
[SPELL/DK] RIME

### ISSUE THREAD

**Issue by pipposo** [tobmaps/TrinityCore#122]
FIX mangos
http://getmangos.com/community/topic/12187/9244fixrime/

wowhead
http://old.wowhead.com/search?q=rime#talents

bug in trinitycore
Howling Blast without using runes .. But unfortunately it never procs after an Obliterate

**Comment by pipposo** [comment]
tobmaps, news?

**Comment by tobmaps** [comment]
tested, works for me

You can try

```
update spell_proc_event set CustomChance=100 where entry=59057; 
```

to test, ofc you should set 0 after you finish ^^
