### ISSUE TITLE
Шадов форма, и друдские формы

### ISSUE THREAD

**Issue by L30m4nc3r** [tobmaps/TrinityCore#123]
Облик тьмы - это стойка у темных пристов.
И формы друидов, мишка итд.
Часто зависает... При выходе с формы в дуели, в неё зайти невозможно, шанс.
Тоже самое на арене или бг, просто в неё войти нельзя.
Можно решить как-то проблему?

**Comment by tobmaps** [comment]
и какой же давности у вас Тринити стоит?

**Comment by L30m4nc3r** [comment]
пару дней назад мердж был

**Comment by Ramusik** [comment]
В офф репо недавно точно был коммит, который это исправил. У меня проблем нет

**Comment by Ramusik** [comment]
https://github.com/TrinityCore/TrinityCore/commit/cb3e6dbce325290fd649ce469adc253fee54f844

**Comment by L30m4nc3r** [comment]
Есть у меня это в ядре. Давно как уже.

**Comment by tobmaps** [comment]
Тогда без понятия, пока сам не столкнусь врятли что-то выйдет

**Comment by L30m4nc3r** [comment]
В коммите я так понял потдвердили.
