### ISSUE TITLE
Professor Putricide

### ISSUE THREAD

**Issue by Craghorn** [tobmaps/TrinityCore#124]
Mutated Abomination on 25 ICC difficulty can't eat slime pools.
Use ability just drop user from vehicle and despawns it.
Mutated Abomination id 25 38285
Eat Ooze Spell id 72527
On 10 ICC difficulty it's working fine. If it helps.
Mb change spells from Vehicle Mutated Abomination 10 to Vehicle Mutated Abomination 25?

**Comment by tobmaps** [comment]
better to not write issues about scripts to my tracker, i'm anyway will not work with scripts

**Comment by Craghorn** [comment]
ok)sry

**Comment by tobmaps** [comment]
you should report about your problem to the main tracker of TrinityCore, only Shauren works at ICC
