### ISSUE TITLE
[Warlock] Всевластный суккуб

### ISSUE THREAD

**Issue by Revive-TC** [tobmaps/TrinityCore#125]
Талант "Всевластный суккуб" (http://ru.wowhead.com/spell=18756) работает, но не до конца: действия способностей "Соблазн" и "Простая невидимость" продлеваются на 10/20/30%, но время применения "Соблазн" (http://ru.wowhead.com/spell=6358) не сокращается, т.е. не работает первая часть описания таланта: Сокращает время применения способности "Соблазн" на 22/44/66%.

**Comment by tobmaps** [comment]
дожили. Постят уже исправленные баги... [p62]
