### ISSUE TITLE
Enchant Weapon - Berserking

### ISSUE THREAD

**Issue by L30m4nc3r** [tobmaps/TrinityCore#127]
http://www.wowhead.com/spell=59621
Перестала прокать.

**Comment by tobmaps** [comment]
только что зачарил 2 штуки на своего рогу и пошел бить манекен - отлично прокает. Стоит свежак из моего форка

**Comment by L30m4nc3r** [comment]
Подскажите, где код спелла, директорию, где я могу найти и выдернуть.
Или-же он присуствует у вас в одном из патчей?

**Comment by giorqa** [comment]
tobmaps ti ochin xarasho trudisha ia toze xaxhu znat c++ kak ti shtobis delat servera ka tii :)

**Comment by tobmaps** [comment]
L30m4nc3r, оно работает на чистом тринити
