### ISSUE TITLE
[Warrior] - Taste for Blood (absorb)

### ISSUE THREAD

**Issue by Jildor** [tobmaps/TrinityCore#129]
UPDATE `spell_proc_event` SET `procEx` = 0x00040000 WHERE `entry` IN (56636, 56637, 56638);

http://code.google.com/p/trinitycore/issues/detail?id=2614

https://github.com/TrinityCore/TrinityCore/issues/922

thx.

**Comment by tobmaps** [comment]
i know about this fix but can't find any confirmations that this one really works in this way at blizzard servers

**Comment by Jildor** [comment]
please, see http://code.google.com/p/trinitycore/issues/detail?id=2614 comments and http://www.youtube.com/watch?v=vFQl7JStwu4

Minute 2:50 - 3:00
thx :D

**Comment by tobmaps** [comment]
good video :)

**Comment by tobmaps** [comment]
will be fixed in official repo

**Comment by kbinside** [comment]
for now taste fo blood does not proc at all.

**Comment by tobmaps** [comment]
it doesn't proc from absorbed attacks - it's okay

**Comment by kbinside** [comment]
i know that, but it should proc instantly when absorb break, not to wait these 6 seconds till it proc, couse per those 6 seconds enemy get another one absorb.

**Comment by tobmaps** [comment]
hm, need to check this case...
