### ISSUE TITLE
[Hunter] Explosive Trap

### ISSUE THREAD

**Issue by 3kids** [tobmaps/TrinityCore#13]
How to reproduce:
1. Explosive trap somebody.
2. Watch the numbers
- What is the expected output?
  It should do instant damage when triggered
- What do you see instead?
  I can see no damage when it triggers, only the periodic damage.
- Please provide any additional information below.

It does work if you do .cast "explosivetrapid"

**Comment by tobmaps** [comment]
it works fine for me, maybe you aren't installed 57_spell_damage_bugfix.sql
Are you sure that you installed _only_ my patches?
