### ISSUE TITLE
[Druid] - Starfall AoE

### ISSUE THREAD

**Issue by Jildor** [tobmaps/TrinityCore#131]
the victim of the stars also suffer from AOE damage, while only nearby friendly targets of the victim should suffer from the AOE produced by starfall on him, and he should suffer from AOE produced by stars hitting his friends [victims in 5 yards of each other or less]

http://code.google.com/p/trinitycore/issues/detail?id=3970

Thx.

**Comment by kbinside** [comment]
Starfall hit too hard (wrong sp coefficient) and hit for 1 to 3 hits at once.

**Comment by Wattiqelumes** [comment]
coefficient fix

-- Starfall
DELETE FROM `spell_bonus_data` WHERE `entry` IN (50294,53188,53189,53190,50288,53191,53194,53195);
INSERT INTO `spell_bonus_data` VALUES
(50288,0.3,-1,-1,-1,'Druid - Starfall (DIRECT)'),
(50294,0.13,-1,-1,-1,'Druid - Starfall (AOE)');

**Comment by kbinside** [comment]
and this to offical repo

**Comment by Jildor** [comment]
Any solution for AOE tobmaps?

Thx.

**Comment by tobmaps** [comment]
Fixed in official repo
