### ISSUE TITLE
[Talent/Spell] Lava Burst

### ISSUE THREAD

**Issue by kbinside** [tobmaps/TrinityCore#138]
Lava Burst deal to low damage, something wrong with spell or talents which should increase its damage:
Lava Burst -> http://old.wowhead.com/spell=51505
Call of Flame -> http://old.wowhead.com/spell=16160
Lava Flows -> http://old.wowhead.com/spell=51482
Shamanism -> http://www.wowwiki.com/Shamanism_(talent) 
Glyph of Lava Burst -> http://www.wowwiki.com/Glyph_of_Lava

something wrong with sp scaling.

**Comment by tobmaps** [comment]
for me it works according damage shown in DrDamage addon so i can't see any bug there, if you find what exactly bugged/missed then you can reopen issues
