### ISSUE TITLE
Immolate

### ISSUE THREAD

**Issue by Wattiqelumes** [tobmaps/TrinityCore#143]
Can't crit on DOT damage.

**Comment by tobmaps** [comment]
can't reproduce. It does crit from DOT damage for me, seems you missed some SQL updates from TrinityCore (yes, it works in official core)

**Comment by Wattiqelumes** [comment]
Doesn't work for me even on a clean one.. Even tried on a few other trinity servers (Molten, etc.) and it's bugged there as well. :(

**Comment by tobmaps** [comment]
1) Drop database `world`;
2) download latest TDB
3) close few wrong tickets

**Comment by Wattiqelumes** [comment]
Well, could you be so kind to write me a small and fast SQL fix for it than, please? I mean, I've done too much work to dump/drop everything.

**Comment by Ramusik** [comment]
DELETE FROM `playercreateinfo_spell` WHERE `Spell`=75445;
INSERT INTO `playercreateinfo_spell` VALUES (0, 9, 75445, 'Demonic Immolate');

Already in TDB

**Comment by Wattiqelumes** [comment]
Great find, Ramusik. Thank you SO much! =D
