### ISSUE TITLE
Blood-Caked Blade

### ISSUE THREAD

**Issue by Wattiqelumes** [tobmaps/TrinityCore#145]
Blood-Caked Blade doesn't require a weapon.

**Comment by tobmaps** [comment]
can't reproduce. I've removed my weapon and this one doesn't proc now

**Comment by tobmaps** [comment]
i think you have very ugly database

**Comment by Wattiqelumes** [comment]
=(
But all I applied were vendors, playercreateinfo_\* stuff and SQL's from your repo. :s

**Comment by tobmaps** [comment]
still can't reproduce and nobody else confirmed, so... closed
