### ISSUE TITLE
Слияние со тьмой + Облик тьмы

### ISSUE THREAD

**Issue by L30m4nc3r** [tobmaps/TrinityCore#146]
Вообщем суть бага.
Игрок ( Темный Жрец )
Садится на маунта.
Жмет "Облик тьмы"
Затем жмет, "Слияние со тьмой."
Снимает с бафов "Облик Тьмы"
И ждет пока закончится действие "Слияние со тьмой"
Вот такой итог:

http://s46.radikal.ru/i113/1105/7d/df71562c646e.png

**Comment by tobmaps** [comment]
Это из-за SPELL_ATTR0_DISABLED_WHILE_ACTIVE такая байда с ним. В Spellauras.cpp вот этот код

```
caster->ToPlayer()->AddSpellAndCategoryCooldowns(m_spellProto, castItem ? castItem->GetEntry() : 0, NULL, true);
```

добавляет нам бесконечный кд. Возможно его не всегда удается убрать с помощью

```
caster->ToPlayer()->SendCooldownEvent(GetSpellProto());
```

Вообще начинаю подумывать что тут ещё и 49868 замешан, у него на ту же категорию кд запускается
