### ISSUE TITLE
[Priest] - Lightwell

### ISSUE THREAD

**Issue by Jildor** [tobmaps/TrinityCore#15]
Spell:  http://old.wowhead.com/spell=724
Without being in combat is good, lasts for 10 uses or 3 minutes.
Being in combat is 3 minutes, do not consume charges.

NPC: http://old.wowhead.com/npc=31897
ScriptName: npc_lightwell

Thx

**Comment by Jildor** [comment]
I think is in:
src/server/scripts/World/npcs_special.cpp

thx

**Comment by tobmaps** [comment]
i think it shouldn't get combat mode and even moving
Maybe it can be solved through DB by setting Civilian flag or something like that

**Comment by Jildor** [comment]
Solved in 

https://github.com/tobmaps/TrinityCore/commit/398c616094d8db275c1040daee73f87c1a0a4ff7

Thx
