### ISSUE TITLE
Sanctified Retribution, Arcane Empowerment & Ferocious Inspiration

### ISSUE THREAD

**Issue by Wattiqelumes** [tobmaps/TrinityCore#153]
They all still stack. I got this SQL and it still doesn't work!

DELETE FROM `spell_group` WHERE `id` IN (2000,2001,2002,2003);
INSERT INTO `spell_group` VALUES
-- Percentage Damage Increase
(2000,63531), -- Sanctified Retribution
(2001,31579), -- Arcane Empowerment
(2002,75593), -- Ferocious Inspiration
(2003,-2000),
(2003,-2001),
(2003,-2002);
DELETE FROM `spell_group_stack_rules` WHERE `group_id` = 2003;
INSERT INTO `spell_group_stack_rules` VALUES (2003,1);

**Comment by tobmaps** [comment]
because you forgot to install [p29], as usually :)

**Comment by Wattiqelumes** [comment]
Same goes for Blessing of Sanctuary & Renewed Hope. (works with Vigilance)

This is the fix you used to fix it:
-- Blessing of Sanctuary vs Vigilance
UPDATE `spell_group` SET `spell_id` = 68066 WHERE `id` = 1091 and `spell_id` = 47930;
UPDATE `spell_group` SET `spell_id` = 20912 WHERE `id` = 1092 and `spell_id` = 20911;

Could you do the same with renewed hope?

**Comment by tobmaps** [comment]
it already doesn't stacks in my fork, just watch at the damage income

**Comment by Wattiqelumes** [comment]
It doesn't? But I applied every single update about stacking behavior.. What is this! D:

**Comment by tobmaps** [comment]
icons stacks, but the effects - no. As i said - check incoming damage, it doesn't increased if you apply both auras

**Comment by tobmaps** [comment]
as i see no reply, then it works ok, then closed :)

**Comment by Wattiqelumes** [comment]
Sorry I kinda forgot about this. Yeah it works. :D
I've got to apply that patch.. 29 I think.. x)
