### ISSUE TITLE
Inferno

### ISSUE THREAD

**Issue by Wattiqelumes** [tobmaps/TrinityCore#155]
1. Summoning an Inferno doesn't allow you to use Soul Link on it.
2. Inferno lasts only 30-40 seconds (diminishing return problem?).
3. White hits are doing 180-200. Damage formula is WAY too low.
4. It scales with spell power I believe. 100%.. Look into that, please.
5. You don't get a pet bar when you summon it.

**Comment by tobmaps** [comment]
it's very difficult to get any info about it for 3.3.5, most of videos from youtube comes from older versions where it was worked in other way :/

**Comment by Wattiqelumes** [comment]
http://youtu.be/9pulx5N0t start at 8:05
http://youtu.be/N1SVHfyqrhw start at 9:40
