### ISSUE TITLE
Arcane Missiles

### ISSUE THREAD

**Issue by Wattiqelumes** [tobmaps/TrinityCore#159]
Since some days (one or two weeks) Missile Barrage started to bug. When Missile Barrage is active and you try to cast Arcane Missiles, it gets interrupted somehow.
Might be a bug only for me though, I am just really confused what caused this.

**Comment by tobmaps** [comment]
works fine for me

**Comment by Wattiqelumes** [comment]
Oh. As I though..
It got bugged after implementing this SQL (all from you), but reverting it makes no difference to the bug. :(
http://pastebin.com/k3aqsmCB

**Comment by tobmaps** [comment]
because this can't be related to my SQL, i didn't even touched this stuff - it works fine even at clean TrinityCore. I only can recommend you to try with clean DB and core

**Comment by Wattiqelumes** [comment]
I've implemented too many things to clear up my whole database and core. For some reason it got bugged after that SQL, but reverting it makes no difference. I'm sooooo confused! :s
