### ISSUE TITLE
[Spell/Warrior]Recklessness

### ISSUE THREAD

**Issue by pipposo** [tobmaps/TrinityCore#16]
http://www.wowwiki.com/Recklessness
http://www.trinitycore.org/t/trinitycore/ticket/888
http://www.trinitycore.org/t/trinitycore/ticket/1025

**Comment by tobmaps** [comment]
not so easy to fix, maybe later...

**Comment by pipposo** [comment]
tobmaps ok, meanwhile thanks for the reply, I look.

**Comment by tobmaps** [comment]
fixed in [p138]
