### ISSUE TITLE
[Mage] Combustion

### ISSUE THREAD

**Issue by HUNTERok** [tobmaps/TrinityCore#17]
Very ancient bug, don't fixed yet. 
More info at http://www.trinitycore.org/t/trinitycore/ticket/78

Critical bug.

**Comment by tobmaps** [comment]
I know about bug but don't have so much time to test some patches that i already founded, maybe later...

**Comment by pipposo** [comment]
in spellauras.cpp
http://paste2.org/p/1367499

**Comment by HUNTERok** [comment]
Pipposo, crap code detected. I think that this fix not work)

**Comment by maxxx** [comment]
проблема в том, что бывает ситуация, когда у 28682 10 стаков, а у 11129 3 заряда и они не снимаются. Бажится массовками и огненной броней, а так же дуал спеком. Более менее помогает http://pastebin.com/nFQ7s4ra

**Comment by tobmaps** [comment]
на мангосе таких проблем вообще нет, быть может оттуда возьму

**Comment by tobmaps** [comment]
already fixed in official repo
