### ISSUE TITLE
Taunt

### ISSUE THREAD

**Issue by ghost** [tobmaps/TrinityCore#172]
in the arena player can with taunt ability put the another player to combat

WowWiki: http://www.wowwiki.com/Taunt_(warrior_ability)

"Taunt has no effect on enemy players in PvP"

**Comment by tobmaps** [comment]
"no effect" doesn't means that it shouldn't put you into combat. Provide more accurate info, videos for example

And about "no effect" - I've already implemented it, if you try to taunt player it just says "Immune"

**Comment by ghost** [comment]
it works fine, i just told some ppl from ofic
