### ISSUE TITLE
Dual talent specialization

### ISSUE THREAD

**Issue by ghost** [tobmaps/TrinityCore#176]
core https://github.com/tobmaps/TrinityCore/commit/d8eda844400b7f5ef5206103bd1988bc81aceeae
ytdb 600

there is a huge bug with learning DTS, it does not take your gold for teaching and if you are learning this the spell cast bar = DTS is very fast so it is probably the main problem with no gold lost

**Comment by tobmaps** [comment]
because it should be fixed through DB after this commit 0bde74eff60be78b39c1e3cc129b05886e7eb87b

So you should blame your DB provider
