### ISSUE TITLE
Gouge

### ISSUE THREAD

**Issue by Wattiqelumes** [tobmaps/TrinityCore#177]
Damage formula is wrong. Should be the following:
(AP \* 0.21) + 1

**Comment by tobmaps** [comment]
It works fine for me, don't forget about target's armor value ;)

**Comment by Wattiqelumes** [comment]
Please try better, it's really bugged for me. :(

Tested in PvE..

**Comment by tobmaps** [comment]
in PvE most mobs has armor, try in PvP vs nude player and you will see :)

**Comment by tobmaps** [comment]
works for me again, i've got same values that shown in DrDamage addon. You should test with ".aura 74367" at your target.
