### ISSUE TITLE
[Druid] Starfall

### ISSUE THREAD

**Issue by Ramusik** [tobmaps/TrinityCore#18]
Коэффициенты в spell_bоnus data занижены. Согласно изменениям патча 3.3.3 урон от звездопада значительно увеличен и согласно wowwiki: [Starfall] 30% , [Starfall]AoE  13% http://www.wowwiki.com/Spell_power_coefficient.

Фикс:

DELETE FROM `spell_bonus_data` WHERE `entry` IN (50294, 53188, 53189, 53190, 50288, 53191, 53194, 53195);
INSERT INTO spell_bonus_data (entry, direct_bonus, comments) VALUES
(50288, 0.3, "Druid - Starfall (DIRECT)"),
(50294, 0.13, "Druid - Starfall (AOE)");

Насколько мне известно, если спелл имеет ранги в spell_ranks, то в таблице spell_bonus_data достаточно указать только 1 ранг заклинания и автоматически коэффициенты применяться к остальным рангам. Если это не так - то подправьте меня

P.S. Хорошее репо. Напоминает репозиторий Insider'a с мангоса. Желаю успешной дальнейшей работы, постараюсь помочь с контрибуцией

**Comment by tobmaps** [comment]
я смотрю у вас ещё и на ядро фикс для этого спелла есть ;) Ок, добавлю всё. Судя по тестам с Dr.Damage урон с фиксом соответствует

**Comment by tobmaps** [comment]
в [p97]
