### ISSUE TITLE
Cleanse issues

### ISSUE THREAD

**Issue by Anonimo17** [tobmaps/TrinityCore#180]
Core rev: https://github.com/tobmaps/TrinityCore/commit/d8eda844400b7f5ef5206103bd1988bc81aceeae

Almost every spell is giving "Nothing to dispell".
As you can see in the picture I was trying to dispell the other dev who had "Devouring Plague", "Vampiric Touch" and "Mind Flay" (not sure that this one is dispellable) on him:  http://img805.imageshack.us/img805/6181/cleanse.jpg

Did I do something wrong or is it supposed to be like that?

**Comment by tobmaps** [comment]
ok, thank you for report. I will rewrite my patch and add new version soon

**Comment by tobmaps** [comment]
fixed
