### ISSUE TITLE
Power type vehicle

### ISSUE THREAD

**Issue by codels** [tobmaps/TrinityCore#185]
https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Entities/Vehicle/Vehicle.cpp#L71
в коде видно что первое заклинание которое показывает какой тип энергии используется, то он и устанавливает (энергия или манна), но если заклинание ничего не требует то по умолчанию будет установлена манна, а если последующие заклинания будут требовать не манну, то их не возможно будет использовать... (проверка типа энергии вываливается break'ом после первой проверке по идее...)
исправить можно в принципе сравнивая перед тем как установить тип манна сколько её требуется, или по умолчанию установить манна и если у транспорта будет хоть один спел требования энергии, установить энергию...

Данная проблема наблюдается за 
https://github.com/TrinityCore/TrinityCore/issues/1263#issuecomment-1333808
где первое заклинание (не знаю правильно ли оно установлено) не требует ничего, а второе требует энергию, так как первое ничего не требует, тип энергии установлен как манна. Правится либо это все дело в ядре, либо надо правильно расставлять заклинания.

**Comment by tobmaps** [comment]
вообще там проверка на ману лишняя по-моему

**Comment by tobmaps** [comment]
исправил в оффрепо

**Comment by codels** [comment]
скорее это для фана))) манна... а так возможно у кого то есть, не помню когда на драконе у дк летаешь там энергия или манна, но все же если что можно было бы изменить слегка логику, выдавать манну только если спелы не используют другие типы энергии. Спасибо.

**Comment by tobmaps** [comment]
пока мана вообще не выдается ни при каких обстоятельствах, впрочем и моего изменения также было. Ниразу не слышал чтобы вехиклы юзали ману
