### ISSUE TITLE
Spell Eyesore Blaster

### ISSUE THREAD

**Issue by codels** [tobmaps/TrinityCore#187]
http://www.wowhead.com/spell=29142
Должен бить в %, править не долго =) Кстати может у таких заклинаний есть какой-то специфический флаг?

**Comment by tobmaps** [comment]
флага не нашел к сожалению

**Comment by codels** [comment]
ну тогда остается пока в кейс это все пихать а потом искать что-то общее у таких заклинаний...

**Comment by codels** [comment]
мб это ещё связано как-то с заклинаниями где манна/жизни восстанавливается не в % а в кол-ве и тоже куча всяких костылей в ядре на этот счет налеплено... скорее есть общая какая-то черта для всего этого...

**Comment by tobmaps** [comment]
ждите в оффрепо
