### ISSUE TITLE
[spell] Divine Storm

### ISSUE THREAD

**Issue by L30m4nc3r** [tobmaps/TrinityCore#194]
http://wowdata.ru/spell.html?id=53385

Божественная буря
Должна восстанавливать игроку  и группе здоровье.
Раньше работало, сей же нет, она не хилит. Вообще.

Core Rev: https://github.com/TrinityCore/TrinityCore/commit/fb9896bbc7966a3d00e82a42c1e26a4c501ce2e9

**Comment by Jildor** [comment]
This fix: http://code.google.com/p/trinitycore/issues/attachmentText?id=3289&aid=7333250760897586103&name=trinitycore_rev10155.patch&token=cc685882aac74a9a39bc680df22fdb6e

By DrTenma works.

**Comment by L30m4nc3r** [comment]
If this fix works for some reason would not add to the offical repository?

**Comment by tobmaps** [comment]
У меня всё работает, потому что патч давно в репозитории. Не первый раз прошу "Не строчите иссуи багов которых в моем репо давно нет"
