### ISSUE TITLE
[talents] stack bug

### ISSUE THREAD

**Issue by L30m4nc3r** [tobmaps/TrinityCore#198]
Таланты зависают, пока не понятно каким образом.
Сейчас покажу скрин-шоты.
- http://s41.radikal.ru/i091/1106/c8/adf5072e5b30.jpg
- http://s004.radikal.ru/i208/1106/4a/3e25cee103c3.jpg
- http://s59.radikal.ru/i165/1106/80/700098b702d0.jpg
- http://s008.radikal.ru/i304/1106/07/680cf77901f5.jpg

Талант: http://ru.wowhead.com/spell=47260
По моим наблюдением как я понял, он вообще работает когда как.
Когда 3 заряда используются, нормально, а когда вообще 3 заряда весят и не используются, может и на 1 заряде зависнуть.

Помоему он перебивается если действовать по такой ротации:

Применен символ: http://ru.wowhead.com/item=42454

http://ru.wowhead.com/spell=348 > http://ru.wowhead.com/spell=17962 > Дальше идут заклинания разрушения.
Оставляем в запасе 1 заряд хотябы, у нас еще не окончилось действие вот этого заклинания: http://ru.wowhead.com/spell=348 > пока весит 1 заряд, юзаем снова http://ru.wowhead.com/spell=17962 > и на 3 заряде, снова каст будет затупленный и заряд останется висеть...
А если его перебафывать то хаст будет замедлен всегда, пока мышкой не снимешь его с полосы бафов.
- http://i060.radikal.ru/1106/cb/74591d7505d5.jpg
- http://s55.radikal.ru/i148/1106/54/d2c0afe1939b.jpg
- http://i081.radikal.ru/1106/59/ed4b864257af.jpg
- http://s006.radikal.ru/i215/1106/e4/3c278a5bff22.jpg
- http://i062.radikal.ru/1106/90/2071e2269e72.jpg
- http://s48.radikal.ru/i119/1106/63/83e614d9c078.jpg
- http://s57.radikal.ru/i157/1106/8d/d3f58f73fa0c.jpg

Анологично талант у шаманов:
http://ru.wowhead.com/spell=51564
Срабатывает от заклинания:
http://ru.wowhead.com/spell=61295

Так-же заряды зависают, и не используются...
- игроки просто теряют очки талантов, и играть становиться не возможно.

Ревизия ядра: https://github.com/TrinityCore/TrinityCore/commit/fb9896bbc7966a3d00e82a42c1e26a4c501ce2e9
Ревизия базы данных: YTDB 602

**Comment by tobmaps** [comment]
это проблема со спеллмодами. QAston собирался доделывать свой патч на них (я имею его первую версию) после внедрения новой прок системы. Пока могу предложить только ждать... ибо править что-либо в текущей спеллмод системе почти не имеет смысла

**Comment by L30m4nc3r** [comment]
работало нормально все, а еще и госсипы, зачем все усложнять и один и тот же код миллион раз переписывать.

**Comment by tobmaps** [comment]
Потому что нужно продвигаться, а не хранить кособокий код (который еле как, но работает) годами

**Comment by L30m4nc3r** [comment]
Ну чтож, тогда будем ждать и надеяться, что QAston "Начнет" это дело и напишет патч.
