### ISSUE TITLE
Символ удара ящера

### ISSUE THREAD

**Issue by Ramusik** [tobmaps/TrinityCore#199]
Символ удара ящера: http://db.uawow.com/?spell=63086

Срабатывает не только от удара ящера, но и от Укуса мангуста. Хотя не должен.

Фикс:
-- Glyph of Raptor Strike
DELETE FROM `spell_proc_event` WHERE `entry`=63086;
INSERT INTO `spell_proc_event` VALUES 
(63086, 0x00, 9, 0x00000000, 0x00000000, 0x00010000, 0x00000000, 0x00000000, 0, 0, 0);

**Comment by tobmaps** [comment]
добавил в оффрепо
