### ISSUE TITLE
[Mage] - Invisibility

### ISSUE THREAD

**Issue by Jildor** [tobmaps/TrinityCore#2]
Spell: http://old.wowhead.com/spell=66

Error: not out of combat

thx

**Comment by tobmaps** [comment]
as i see Sanctuary effects is broken for now in original TrinityCore, spell 54661 used for closing combat with these spell just does nothing for npc's, it works fine vs pets but not vs other npc's

**Comment by tobmaps** [comment]
made more test and see that in void Spell::EffectSanctuary
    Unit::AttackerSet const& attackers = unitTarget->getAttackers();
    for (Unit::AttackerSet::const_iterator itr = attackers.begin(); itr != attackers.end();)
    {
        if (!(_itr)->canSeeOrDetect(unitTarget))
            (_(itr++))->AttackStop();
        else
            ++itr;
    }

returning

```
        ++itr;
```

but should return

```
        (*(itr++))->AttackStop();
```

So as i see we fails

```
    if (!(*itr)->canSeeOrDetect(unitTarget))
```

**Comment by Jildor** [comment]
I'm sorry, I do not quite understand, I have to apply some of what you put there?

thx

**Comment by tobmaps** [comment]
no you don't need to apply this. I just marked a problematic code

**Comment by Jildor** [comment]
ah, oks.

**Comment by tobmaps** [comment]
lol, this problem only with City guards. I've tested it with other types of npc's and seems all is ok
Looks like they have some stealth detect auras. Maybe it happen because we have incorrect stealth detection formulas for npc's or these guards has some "worderful" code in their scripts

If you notice that problem with other types of npc's than guards and bosses then you haven't installed some of my patches. Better to install all of them before post any Issues to this tracker :/

**Comment by Jildor** [comment]
No, reproduce with all npc agressive, but example http://old.wowhead.com/npc=822 
Attack npc cast Invisibility and run...npc follow.

**Comment by tobmaps** [comment]
even if you are at 80 lvl? I've tested this npc with my 80 lvl rogue, used vanish and npc forget about me and returns to his spawn place.
If you doing the same then you aren't installed some of my patches. As i said - better for you to use all of them (or atleast most) and only then post any Issues to the tracker

As i understand you aren't installed patches 24,34,56

**Comment by Jildor** [comment]
Yes yes, I'm tested with gnome mage lvl 80 :D

**Comment by Jildor** [comment]
o.O I apply this issues and I think works good.

I love you
