### ISSUE TITLE
[Shaman] Тотем оков земли \ Тотем трепета

### ISSUE THREAD

**Issue by Ramusik** [tobmaps/TrinityCore#20]
Эффекты Тотема оков земли и Тотема трепета должны срабатывать во время установки этих тотемов. В настоящий момент они срабатывают только через 3 секунды.

Источник:
\/ http://www.wowwiki.com/Tremor_totem - This totem will immediately remove any applicable ailments when it is first down, then subsequently attempt to remove fear/sleep/charm effects every 3 seconds. 
\/ http://www.wowwiki.com/Earthbind_Totem - http://code.google.com/p/trinitycore/issues/detail?id=843

Патч (автор - я):
http://pastebin.com/jABvw4cK

**Comment by tobmaps** [comment]
добавил в [p100]
