### ISSUE TITLE
[Warrior] - Titan's grip

### ISSUE THREAD

**Issue by Jildor** [tobmaps/TrinityCore#203]
Spell: http://www.wowhead.com/?spell=46917

Problem: You have Titan's Grip talent and you have two weapons two handed equipped, change your talent and still them and you can attack with them.

Thx.

**Comment by tobmaps** [comment]
```
OffhandCheckAtSpellUnlearn = 1
```

and it's done, i hope ^^

**Comment by Jildor** [comment]
....omg

I LOVE YOU!
