### ISSUE TITLE
[Paladin] - Greaters blessings

### ISSUE THREAD

**Issue by Jildor** [tobmaps/TrinityCore#204]
cb0792aa2e7d34065c166f5435e7e059c37e59f3
29e11c0ce1827d714bf27f4d3b53b0f6ae983ef8

When apply this fix, if is two o more paladin in group/raid and cast Blessing of Kings and Blessing of Might among themselves, only have 1 buff (between paladins).

That has to be? I don't know.

I think is with the Greaters blessings.

I think is only second caster, stack only one blessing and remove last blessing.

Thx.

**Comment by tobmaps** [comment]
dunno how it can happen ofc if you didn't added some unneeded DB data into spell_group

**Comment by Jildor** [comment]
Can you tell me how to check?
<pre>SELECT \* FROM spell_group WHERE spell_id IN (xxx....);</pre> ??
Thx.

**Comment by Jildor** [comment]
<pre>SELECT * FROM spell_group WHERE spell_id IN (25898,43223,25782,25916,27141,29381,33564,43940,48933,48934,25899,25894,25918,27143,48937,48938);</pre>


1002 - 25782
1005 - 25894
1006 - 25898
1006 - 43223
1007 - 25899

as in TDB.

I don't know.

Can you reproduce?, only make two paladins and make group and cast two Greaters blessings.

**Comment by tobmaps** [comment]
then check spell_group_stack_rules with those groups, and check stack_rule values for them, it should have value = 2 for rule that used in Blessings

**Comment by Jildor** [comment]
all value = 1

as in TDB.

then update to 2? :S

**Comment by Jildor** [comment]
<pre>UPDATE spell_group_stack_rules SET stack_rule = 2 WHERE group_id IN (1006,1002,1005,1007);</pre>


Still wrong :S

**Comment by Jildor** [comment]
The same with warriors, with Battle Shout & Commanding Shout, the second caster lost first buff when cast second buff.

can anyone confirm?

Tobmaps any solution?

Thx.

**Comment by tobmaps** [comment]
Battle Shout & Commanding shout works fine for me, tested with 2 warriors in group and both warriors have those buffs, i'm sure you applied something wrong

**Comment by Jildor** [comment]
I'm only revert your patch: https://github.com/Jildor/ZoneLimit/commit/7f2e5ce3c9088e6841b6074e9a48943535bb57bf

And works fine, if apply, work wrong, any solution? :S

Thx.

**Comment by tobmaps** [comment]
you can try to use only my core and clean TDB without any additional patches to test

**Comment by Jildor** [comment]
Sorry, when I asked:
"Then to fix apply https://github.com/tobmaps/TrinityCore/commit/cb0792aa2e7d34065c166f5435e7e059c37e59f3 and https://github.com/tobmaps/TrinityCore/commit/29e11c0ce1827d714bf27f4d3b53b0f6ae983ef8 no? or any more?"

In https://github.com/tobmaps/TrinityCore/issues/3

You told me any more.

I see this: https://github.com/tobmaps/TrinityCore/commit/6c72ee8d52dc3911d1384bd20b2a4bf06010be6a

I apply and test, and now confirm or not.

**Comment by Jildor** [comment]
Solved, sorry for the inconvenience.

Thx.
