### ISSUE TITLE
Judgements of the Pure 

### ISSUE THREAD

**Issue by ghost** [tobmaps/TrinityCore#206]
There is a bug with procing of Judgements of the Pure , it must proc on absorb too, my friend tests it on official realm so this mechanic must work on absorb too

suggested fix

`UPDATE `spell_proc_event` SET `procEx` = '263168' WHERE `spell_proc_event`.`entry` =54151;`

**Comment by tobmaps** [comment]
it have procEx = 0x40000 (Only Active Spell) that means it will not proc from absorbs, it does proc when actually damage caused, why you add one more procEx when you can just remove unneeded one? And you also should do it for all ranks

right fix

```
UPDATE `spell_proc_event` SET `procEx` = 0 WHERE `entry` IN (53671,53673,54151,54154,54155);
```

**Comment by ghost** [comment]
yes my mistake, can you please explain me why is set `procEx` = 0 and not 0x0000400 ?

**Comment by tobmaps** [comment]
```
why is set procEx = 0 
```

read my previous message again and try to think more ;)

**Comment by tobmaps** [comment]
fixed in TC
