### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by ghost** [tobmaps/TrinityCore#208]
I have compile errors on this revision https://github.com/tobmaps/TrinityCore/commit/5585e26af6f8c1c0c11cf9bcffdc05d10d9864ce

[ 40%]TrinityCore/src/server/scripts/OutdoorPvP/OutdoorPvPWG.cpp: In member function ‘virtual void OutdoorPvPWG::OnGameObjectCreate(GameObject*)’:
TrinityCore/src/server/scripts/OutdoorPvP/OutdoorPvPWG.cpp:883: error: ‘union GameObjectValue’ has no member named ‘building’
TrinityCore/src/server/scripts/OutdoorPvP/OutdoorPvPWG.cpp:888: error: ‘union GameObjectValue’ has no member named ‘building’
TrinityCore/src/server/scripts/OutdoorPvP/OutdoorPvPWG.cpp: In member function ‘void OutdoorPvPWG::RebuildAllBuildings()’:
TrinityCore/src/server/scripts/OutdoorPvP/OutdoorPvPWG.cpp:939: error: ‘class GameObject’ has no member named ‘Rebuild’
TrinityCore/src/server/scripts/OutdoorPvP/OutdoorPvPWG.cpp:940: error: ‘union GameObjectValue’ has no member named ‘building’

**Comment by ghost** [comment]
same

**Comment by ghost** [comment]
Code style change?
building.health to Building.Health

**Comment by tobmaps** [comment]
fixed
