### ISSUE TITLE
[Warriror] - Enrage + Wrecking Crew stack

### ISSUE THREAD

**Issue by Jildor** [tobmaps/TrinityCore#21]
Talent Wrecking Crew stack (all rank) + Enrage stack.
Description: Your melee critical hits Enrage you, increasing all damage caused by X% for 12 sec. This effect does not stack with Enrage.

Thx.

**Comment by tobmaps** [comment]
ok, i can confirm. It can be fixed through spell_group_stack_rules

**Comment by tobmaps** [comment]
fixed in [p103]

**Comment by Jildor** [comment]
thx ^^
