### ISSUE TITLE
[Расовая] Боевой дух

### ISSUE THREAD

**Issue by Ramusik** [tobmaps/TrinityCore#28]
Если в группе несколько дренеев, то бывает, что расовые способности Боевой дух накладываются. 

Фикс (автор - я):
http://pastebin.com/67W6aRaU

**Comment by tobmaps** [comment]
ок, в [p109]

**Comment by Jildor** [comment]
Sorry, a suggestion.

Can you write in English at least?, I do not understand anything T.T
I'm spanish

Thx ^^

**Comment by tobmaps** [comment]
you can use http://translate.google.com/#ru|en| ^^

**Comment by Jildor** [comment]
Yes....but bad traslate :D
