### ISSUE TITLE
[Warlock] Curse of Elements

### ISSUE THREAD

**Issue by Ramusik** [tobmaps/TrinityCore#29]
http://www.wowwiki.com/Curse_of_Elements

Patch 2.1.0 (2007-05-22): Now has a duration of 2 minutes when used on PvP targets. 

Фикс (автор - я):
http://pastebin.com/6R402PJJ

Note: проклятия данного типа не имеют значений в поле SpellFamilyFlags[0], зато имеют значение 512 в поле SpellFamilyFlags[1]

**Comment by tobmaps** [comment]
Вот сюда тоже бы запостить http://www.trinitycore.org/f/index.php?/topic/2051-diminishing-return/

**Comment by Wattiqelumes** [comment]
Doesn't put me in combat either, and doesn't unstealth a rogue.

**Comment by tobmaps** [comment]
```
and doesn't unstealth a rogue.
```

only damaging spells unstealth rogue at TrinityCore, we need more info about what exactly spells should do it... should be a generic rule i think.

**Comment by Wattiqelumes** [comment]
Yeah good idea. Might be something for future?

**Comment by Ramusik** [comment]
Вижу в офф ядро недавно добавили. Можно закрывать
