### ISSUE TITLE
[DK] - Improved Icy Talons

### ISSUE THREAD

**Issue by Jildor** [tobmaps/TrinityCore#3]
Spell:  http://old.wowhead.com/spell=55610/
Description: Increases the melee and ranged attack speed of all party and raid members within 100 yards by 20%, and your own attack speed by an additional 5%.
Error: Also applies to you the 20% when you only have to be 5%

**Comment by tobmaps** [comment]
need more info from offy how it should really works. I've seen at wowhead comments that is should apply both at DK but at next comment another man said that shouldn't :/

**Comment by Jildor** [comment]
sorry, I can only show:

http://www.trinitycore.org/t/trinitycore/ticket/249
http://us.battle.net/wow/en/game/patch-notes/3-3-3

**Comment by tobmaps** [comment]
try [p77]

**Comment by Jildor** [comment]
Solved :D

**Comment by OneB1t** [comment]
im not sure if this is correct on patch 3.3.3 stacking of this talent changed and now i think it must be 45% haste for frost DK (as can be founded on wowhead and few forums)
https://github.com/TrinityCore/TrinityCore/issues/293

**Comment by Jildor** [comment]
If have two dks in group/raid and one change talents can stack two Improved Icy Talons.

Thx.

**Comment by tobmaps** [comment]
think this isn't a bug, they should get haste bonus from other players but just shouldn't benefit from own. And i also think that you didn't applied [p29]

**Comment by Jildor** [comment]
Then to fix apply https://github.com/tobmaps/TrinityCore/commit/cb0792aa2e7d34065c166f5435e7e059c37e59f3  and https://github.com/tobmaps/TrinityCore/commit/29e11c0ce1827d714bf27f4d3b53b0f6ae983ef8 no? or any more?

**Comment by tobmaps** [comment]
yep

**Comment by Jildor** [comment]
I LOVE YOU!
