### ISSUE TITLE
trick of the trade

### ISSUE THREAD

**Issue by pipposo** [tobmaps/TrinityCore#33]
The spell is still not working well:

I do the tricks of the trade, I add this buff "The Threat Caused by damaging your next attack and all actions taken for 6 sec Afterwards Will Be Transferred to the target. In Addition, Caused by damage to the target is Increased by 15% During this time. "correctly.
Then I have an attack any (whether autoattack, a move that generates a combo or that it consumes the same thing happens) and I removed the second part of the buff (this: "In Addition, Caused by damage to the target is Increased by During this time 15%. "leaving only the first part (this one:" The threat Caused by damaging your next attack and all actions taken for 6 sec Afterwards Will Be Transferred to the target. ")

In fact it should happen that applies a buff spell on the player to which I have the spell for 6 seconds and sends him around the threat that son and I apply a buff to me (the one above) that I increases all damage for 20 sec I do 15% happens on the server instead of the buff is applied correctly, but instead to increase all spell damage taken by me for 20 seconds, only increases the damage of the first spell and then takes off.

**Comment by tobmaps** [comment]
```
Even if aggro is not an issue in the fight you're in, the damage boost (particularly if glyphed) is a nice buff for the tank (or even another party member), and thus Tricks of the Trade should be applied as often as is practical in any given fight.
```

taken from here http://www.wowwiki.com/Tricks_of_the_Trade

So it works OK.

**Comment by pipposo** [comment]
k, you can close.
