### ISSUE TITLE
[Hunter] Список нерабочих магий/талантов

### ISSUE THREAD

**Issue by Revive-TC** [tobmaps/TrinityCore#34]
1. [Неудержимое неистовство], должен увеличивать урон питомца на 3/6/9/12/15%. Не работает вообще. 
2. [Свирепое воодушевление], должно увеличивать весь урон питомцу и всем членам группы(рейда) в радиусе 100м от него на 1/2/3%. Увеличивает урон группе(рейду), но не увеличивает урон самому питомцу. 
3. [Родственные души], должен увеличивать урон питомца на 4/8/12/16/20% и скорость передвижения хозяина и питомца на 10%. Скорость увеличивает, а урон питомцу не прибавляет вообще. 
4. [Шипастый ошейник], должен увеличивать урон питомца на 3/6/9%. Не работает вообще. 
5. [Контроль популяции], должен увеличивать урон питомцу и хозяину на 1/2/3%. Увеличивает урон хозяину, но не увеличивает урон питомцу. 
6. [Акульи челюсти], должен увеличивать урон питомца на 3/6%. Не работает вообще.

**Comment by tobmaps** [comment]
Не ну вот не стыдно? :( Ставьте _все_ патчи и всех этих багов небудет

**Comment by tobmaps** [comment]
баг таки был, из-за опечатки в патче [p66]
