### ISSUE TITLE
[Warlock] Господство скверны

### ISSUE THREAD

**Issue by Ramusik** [tobmaps/TrinityCore#35]
Спелл: http://db.uawow.com/?spell=18708

Нашел баг в работе спела: если юзнуть спел и вызвать прислужника - вроде все норм. Но если при вызове пета прервать каст, то следующий каст призыва питомца будет не сниженным, хотя баф висит. 

Т.е. при активной ауре спела http://db.uawow.com/?spell=18708 игрок должен суммонить на 5.5 сек быстрее, не смотря на то, сбивался ли каст или нет

**Comment by tobmaps** [comment]
баг очень древний... ещё добавлю что если замедлить каст тому на ком этот баф то его эффект также заглушается

Думаю откопать его будет ооочень сложно. Это что-то на уровне спелмодов

**Comment by tobmaps** [comment]
тут всё действительно плохо. Посути конкретный легко исправить, но из-за него придется править ещё несколько, а именно http://filebeam.com/314244a706e505a2cc4af49e7093d424.jpg

Причем править придется с добавлением записей на каждый в БД - а это полный бред. Вот в Мангосе ничего добавлять ненужно...

Вот хоть реально оттуда всю прок систему выдирай начиная с этого https://github.com/mangos/mangos/commit/b2260d2e076fdac12f93268e224361cf80b8af3e коммита

**Comment by tobmaps** [comment]
В общем можешь попробовать вот этот патч http://paste2.org/p/1397445 в связке с 

```
DELETE FROM spell_proc_event WHERE entry = 18708;
INSERT INTO spell_proc_event (entry,SpellFamilyName,SpellFamilyMask0,procFlags) values (18708,5,0x20000000,0x4000);
```

ну и другим указанным на скрине тоже придется докидать.

Если кто-то найдет способ как заставить их всех прокать без данных в БД то буду рад, isAlwaysTriggeredAura не катит, сразу говорю

**Comment by tobmaps** [comment]
Придется подождать с этим делом, QAston обещал переделку в прок системе

**Comment by tobmaps** [comment]
Временное решение, пока систему проков не переписали http://paste2.org/p/1418069

**Comment by Ramusik** [comment]
Походу реализовали в офф тринити))

**Comment by tobmaps** [comment]
Ну я уже сказал чем это черевато :) это всё равно придется откатить когда QAston доделает свою прок систему
