### ISSUE TITLE
[Druid] Item T10 Restoration 2P

### ISSUE THREAD

**Issue by Ramusik** [tobmaps/TrinityCore#36]
Не работает бонус 2ч рестора Т10 - http://db.uawow.com/?spell=70658. Покопался в мангосе - у них это исправлено.

У них в SpellAuras это реализовано так:

http://pastebin.com/y5M7dGDb.

Попытался портировать на Тринити - вот что у меня вышло:

http://pastebin.com/tMaFZ2Ea

Но в итоге все равно не пашет. У меня большие сомнения насчет aura->GetModifier()->m_amount . Может быть в этом пробема. Может есть идеи?

**Comment by tobmaps** [comment]
Вот так по сути http://paste2.org/p/1381557
но там всё равно считается неверно... допустим разница между последним хилом без бонуса - 219, с бонусом - 213. 30% явно не пахнет. На вовхеде немного есть инфы...

**Comment by Jildor** [comment]
Sorry, but duplicate: https://github.com/tobmaps/TrinityCore/issues/8 :D

thx

**Comment by Ramusik** [comment]
Проверю - отпишусь. Спасибо

**Comment by Ramusik** [comment]
Че то все равно не канает. Что с сетом, что без сета, при 303 спд хилит за все время действия 2к

**Comment by tobmaps** [comment]
побольше спд сделай, допустим 3к

**Comment by tobmaps** [comment]
По-моему ((ticks-1)\* 100 там лишний, нужно просто делить на 100. Тогда и результат ОК будет
Видимо Laise немного перемудрила :)

**Comment by Ramusik** [comment]
Итак, что мы имеем с ((ticks-1)\* 100 :

без бонуса (2101 спд): 672, 638, 605, 572, 540, 507, 473
с бонусом (2101 спд): 672, 641, 606, 572, 541, 509, 478

Т.е. получается, 672 - 638 = 34 ; 34 - 34*0.3=23.8; 672-23,8=648,2

Т.е. с бонусом на 2 тике должно быть 648,2, а имеем 641. Следовательно, то что есть некорректно. Ща проверю без ((ticks-1)\* 100

**Comment by tobmaps** [comment]
Я вот всё не пойму, на вовхеде в одном из комментов что 1 тик должен больше хилить когда есть бонус (наш код это исключает, да и судя по подсказке не должно его усилять), я замеряю по аддону Dr.Damage - без сета хил почти совпадает, даже чуть больше чем надо. А с сетом нехватает где-то сотки

**Comment by Ramusik** [comment]
Убрал ((ticks-1)\* 100:

без бонуса (2101 спд): 672, 638, 605, 572, 540, 507, 473
с бонусом (2101 спд): 672, 658, 614, 572, 549, 526, 502

Считаем общее снижение исцеления без бонуса: 672 - 473 = 199
с бонусом: 672 - 502 = 170

199 - 199*0.3 = 139.3 

Т.е. в данный момент бонус снижает не на 30%, а около 15%.

В случае Laise еще более запущено: 672 - 478 = 194 (снижение на 2%)

**Comment by tobmaps** [comment]
По сути можно даже так

```
            // Wild Growth = amount + (6 - 2*doneTicks) * ticks* amount / 100
            if (m_spellProto->SpellFamilyName == SPELLFAMILY_DRUID && m_spellProto->SpellIconID == 2864)
            {
                int32 addition = int32(float(damage * GetTotalTicks()) * ((6-float(2*(GetTickNumber()-1)))/100));

                if (GetTickNumber() != 1)
                    // Item - Druid T10 Restoration 2P Bonus
                    if (AuraEffect * aurEff = caster->GetAuraEffect(70658, 0))
                        addition += abs(int32((addition * aurEff->GetAmount()) / 50));

                damage += addition;
            }
```

Мб делить не на 100, а на 50?

**Comment by Ramusik** [comment]
Ща пробну делить на 50, но при этом увеличив СПД. Гляну что получится

**Comment by Ramusik** [comment]
Получилось следующее:

без бонуса (2300 спд): 703, 669, 636, 604, 571, 538, 504. 
с бонусом: 703, 709, 654, 604, 590, 577, 563 

на 2 тике явно не то, хотя общее снижение 703 - 563 = 140 (30%)

**Comment by Ramusik** [comment]
Может должен 1 тик все таки усиливаться?

**Comment by tobmaps** [comment]
Да у меня такое же ощущение. Ведь не зря в одном из комметнов вовхеда писали с увеличением  1 тика. Хотя и остальные 2 без :/ Dr.damage тоже к этому ведет, он редко ошибается

```
            // Wild Growth = amount + (6 - 2*doneTicks) * ticks* amount / 100
            if (m_spellProto->SpellFamilyName == SPELLFAMILY_DRUID && m_spellProto->SpellIconID == 2864)
            {
                int32 addition = int32(float(damage * GetTotalTicks()) * ((6-float(2*(GetTickNumber()-1)))/100));

                // Item - Druid T10 Restoration 2P Bonus
                if (AuraEffect * aurEff = caster->GetAuraEffect(70658, 0))
                    addition += abs(int32((addition * aurEff->GetAmount()) / 50));

                damage += addition;
            }
```

Вот так очень близкие значения с аддоном принимает. Разве что сам по себе Wild Growth хилит больше чем нужно по аддону, т.е. там небольшая погрешность в расчете спд

Вот поэтому я нелюблю фиксить всякие там ПвЕ штучки... в них хрен разберешься

**Comment by Ramusik** [comment]
Да погрешность небольшая, около 20 за все время действия спела. В любом случае фикс на бонус пашет корректно, так что добавляй в репо =)

**Comment by tobmaps** [comment]
в [p126], посути это уже совсем другой патч =) Так что авторство за мной

**Comment by Jildor** [comment]
Sorry, but, how to reproduce the fix?

I cast Wild Growth but I see no change.

Thx

**Comment by tobmaps** [comment]
did you tried to apply [p126]? Or you trying to apply patch from first post or versions from below?

**Comment by Jildor** [comment]
[p126], but I don´t understand well

**Comment by tobmaps** [comment]
it increases heal in summary because it lowers decreasing of heal for all next ticks

**Comment by Jildor** [comment]
thx.
