### ISSUE TITLE
[Item] Dislodged Foreign Object 

### ISSUE THREAD

**Issue by Ramusik** [tobmaps/TrinityCore#37]
Объект из другого измерения - http://db.uawow.com/?item=50348 должен прокать только от атакующих заклинаний.

Фикс. Автор - я

UPDATE `spell_proc_event` SET `procFlags`=0x00010000 WHERE `entry` IN (71602,71645); -- Dislodged Foreign Object

**Comment by tobmaps** [comment]
быть может потом закоммитю если таких ещё больше наберется. Мутить отдельный патч ради 1 фикса вещи как-то не тянет...

**Comment by Ramusik** [comment]
Кстати, там писали насчет травмы, что она не пашет. Вобщем проверил - она срабатывает только от хилящих спелов прямого действия. Не срабатывает от ХоТов. Установка procFlags в 0x00044000 ( 0x00040000 - PROC_FLAG_ON_DO_PERIODIC , 0x00004000 - PROC_FLAG_SUCCESSFUL_POSITIVE_SPELL ) для спелов http://ru.wowhead.com/spell=71868, http://ru.wowhead.com/spell=71865 не помогает. Где-то скрыта загвоздка ...

**Comment by tobmaps** [comment]
он каждого тика ХОТов должно или от наложения 1 раз?

**Comment by Ramusik** [comment]
The proc rate is 1%, but each HoT tick counts. - коммент с вовхеада

Т.е. на каждом тике ХоТа Травма имеет шанс прокнуть, и как пишут на том же вовхеаде:
На первом месте по прокам разумеется будет друид, который спамит реджув :) Если бой хорош для спама реджува, Травма сделает только лучше.

А щас наоборот - друлям само хуже, так как и них травма практически редко прокает

**Comment by tobmaps** [comment]
И толку что вы ему 0x00040000 флаг ставите? он уже есть в дбц ;) Как и от позитивных

**Comment by tobmaps** [comment]
Без вмешательства в ядро ничего не выйдет

**Comment by tobmaps** [comment]
а ещё такие трини есть? С похожим багом всмысле

**Comment by tobmaps** [comment]
ваш патч приняли в TC, закрываю. Для "Травмы" уже есть другой иссуй
