### ISSUE TITLE
Мили Хаст

### ISSUE THREAD

**Issue by Ramusik** [tobmaps/TrinityCore#38]
Патч 3.1:
- Рейтинг скорости: влияние рейтинга на скорость ближнего боя для шаманов, паладинов, друидов и рыцарей смерти повышено на 30%.

На Мангосе есть отличный коммит, который портается очень легко (помню без проблем портал на Тринити 99xx ревизий).

https://github.com/mangos/mangos/commit/9ec5b1cfbedf2b7e2dd3d8b4dd7b1d08574cc446

вобщем вот патчик, правда возможно устарел, http://paste2.org/p/1381766. так как я коммитил у себя уже давно

**Comment by tobmaps** [comment]
Добавил в [p127]. Мельком протестил, видно что хаст теперь реально лучше действует на ДК, других не проверял
