### ISSUE TITLE
Vigilance

### ISSUE THREAD

**Issue by nucleartux** [tobmaps/TrinityCore#39]
http://www.wowhead.com/spell=50720
Собственно вообще не работает.
В ядре вроде как реализовано, наверно я криворукий.
Если будет время проверьте пожалуйста.

**Comment by tobmaps** [comment]
На моем ядре отлично пашет.  Специально пилил...

**Comment by Ramusik** [comment]
у меня тоже норм пашет

**Comment by nucleartux** [comment]
Спасибо :)

**Comment by pipposo** [comment]
https://github.com/TrinityCore/TrinityCore/issues/410
