### ISSUE TITLE
[Shaman] - Hex

### ISSUE THREAD

**Issue by Jildor** [tobmaps/TrinityCore#4]
Spell:  http://old.wowhead.com/spell=51514
If you cast hex target while mounted, the target does not get dismounted

**Comment by tobmaps** [comment]
i can't find any info that it _should_ make target to dismount

**Comment by Jildor** [comment]
Should not be like Polymorph?

thx

**Comment by tobmaps** [comment]
i think so

**Comment by Jildor** [comment]
Can not do anything to dismount as with Polymorph?

thx

**Comment by tobmaps** [comment]
i will do this if i find any actual info that said about this feature. Ofc better to record a video from official ^^

**Comment by Veretos** [comment]
According to wowhead: http://www.wowhead.com/spell=51514/hex#comments:80

By Ichabe (2·20) on 03/18/2009 (Patch 3.0.9)
Funny thing: you don't get dismounted if you get hexed. I got hexed while riding my flying carpet and was able to just fly right on, and out of danger!

**Comment by tobmaps** [comment]
okay

**Comment by Jildor** [comment]
thx
