### ISSUE TITLE
[Ядро] Ненужный код?

### ISSUE THREAD

**Issue by Ramusik** [tobmaps/TrinityCore#40]
Копался в ядре, нашел кусок на реализацию символа вспышки света. 

На 3.3.5. символ вспышки света повышает вероятность крита этого заклинания на 5%, в ядре реализован какой-то хот при наличии этого символа. Походу это устаревший кусок кода:

http://paste2.org/p/1382169

Соответственно и базе:

DELETE FROM `spell_proc_event` WHERE `entry` = 54936;

**Comment by tobmaps** [comment]
Так и есть, устаревший

**Comment by tobmaps** [comment]
в [p132]
