### ISSUE TITLE
[spells] Погром | Исступление

### ISSUE THREAD

**Issue by L30m4nc3r** [tobmaps/TrinityCore#42]
2 таланта у вара Погром и Исступление.
Они должны заменять друг друга, но увы, они не стакаются, тоесть 1 вкачиваем на увелечение физ урона на 10% и еще один такой-же, поидее один заменит другой и не получится 20% увы, у нас же выходит 20%.
Внимательно читаем талант:
http://wowdata.ru/spell.html?id=56614
http://wowdata.ru/spell.html?id=13048

**Comment by tobmaps** [comment]
недавно фиксил... обновляйтесь или ставьте [p103]
