### ISSUE TITLE
Achievements: Spring Fling

### ISSUE THREAD

**Issue by L30m4nc3r** [tobmaps/TrinityCore#43]
http://www.wowhead.com/achievement=2497/spring-fling
Не работает, а ивент "Сад Чудес" скоро окончится.

**Comment by tobmaps** [comment]
не, этот сложно сделать... я пока в ачивах не разбирался

**Comment by Ramusik** [comment]
Можешь пробнуть фикс от Влада:
https://github.com/vlad852/TrinityCore/commit/497221933e8194aea531a042f245a34554c0b0dc

**Comment by tobmaps** [comment]
ну судя по комментам он работает, добавлю

**Comment by tobmaps** [comment]
добавил в [p143]. Проверяйте, если пашет то сами закроете иссуй

**Comment by L30m4nc3r** [comment]
Пашет, закрыл.
