### ISSUE TITLE
[spell/talent death knight] Взрыв трупа | Машина для убийств

### ISSUE THREAD

**Issue by L30m4nc3r** [tobmaps/TrinityCore#44]
http://wowdata.ru/spell.html?id=51328
Всеми уровнями заклинания. Спелл стал слишком баганый.
После мерджа офф TС, он начал бить по 12000+ просьба рассмотреть/пересмотреть.

http://wowdata.ru/spell.html?id=51123
ДК, невкачивают 5 талантов, а вкачивают только 1. Почему же?
Потому-что незачем вкачивать их 2,3,4,5. Потомучто от 1 поинта он срабатывает как от 5 ( Постоянно прокает )
Даже если вкачать их 2,3 без разницы он тупо постоянно вылетает.

**Comment by tobmaps** [comment]
1. Проверим, я его ещё не трогал
2. Машину для убийств уже достаточно давно пофиксил, видимо у вас не моё ядро или же избирательно ставите патчи. Конкретно для Машины убийств - фикс [p22]

**Comment by tobmaps** [comment]
1. Проверил, у меня нормально урон наносит. Либо там какие-то доп условия которые вы не указали, либо это баг с вашим форком/исходниками

**Comment by L30m4nc3r** [comment]
Офф TrinityCore.
- Ваши патчи некоторые.

**Comment by tobmaps** [comment]
Вот именно "некоторые"

**Comment by L30m4nc3r** [comment]
Эх, спасибо...
