### ISSUE TITLE
[Death Knight] Blood Boil

### ISSUE THREAD

**Issue by Ramusik** [tobmaps/TrinityCore#46]
Некорректный коэффициент. Должно быть 6% от АП (DrDamage):

Фикс (автор- я):
DELETE FROM `spell_bonus_data` WHERE `entry` IN (49941,48721);
INSERT INTO `spell_bonus_data` (`entry`,`direct_bonus`,`dot_bonus`,`ap_bonus`,`ap_dot_bonus`,`comments`) VALUES
(48721, 0, 0, 0.06, 0, 'Death Knight - Blood Boil');

Кстати, хотел узнать есть ли разница в "-1" и "0" при указании коэффициентов? Как по мне то использовать "0" более правильно

**Comment by tobmaps** [comment]
-1 позволяет позволяет использовать коэффициенты на усмотрение ядра, 0 тупо запрещает

**Comment by Ramusik** [comment]
Тогда получается, что если использовать -1 то можем получить нежелательное скалирование от СПД или АП. Как я понял, лучше использовать 0, чтобы предотвратить это. Значит я правильно написал запрос

**Comment by tobmaps** [comment]
-1 вроде как быстрее, потому его юзают обычно. + можно отследить баги ядра. В общем там нужно смотреть в каждом конкретном случае. Тупо занулять не дело

вот кстати лучше так

```
update spell_bonus_data set ap_bonus=0.06 where entry=48721;
```

**Comment by Ramusik** [comment]
Тогда не забудь DELETE FROM `spell_bonus_data` WHERE `entry`=49941; так как смысла указывать бонус для 4 ранга нет, так как он присутствует в spell_ranks

**Comment by tobmaps** [comment]
добавил в [p142]
