### ISSUE TITLE
[Priest] Divine Hymn

### ISSUE THREAD

**Issue by Ramusik** [tobmaps/TrinityCore#47]
В настоящий момент не скалируется от СПД. Согласно DrDamage коэффициент составляет 2.193, т.е. 2.193/4 = 0.5483 за тик. 

DELETE FROM `spell_bonus_data` WHERE `entry` = 64844;
INSERT INTO `spell_bonus_data` VALUES 
(64844, 0.5483, 0, 0, 0, 'Priest - Divine Hymn');

**Comment by Ramusik** [comment]
Еще 1 баг: исцеляющий эффект Божественного гимна может быть критический (http://www.wowwiki.com/Divine_Hymn). Но сейчас не критует

Фикс (автор - я):
http://paste2.org/p/1388641

**Comment by tobmaps** [comment]
Его ещё и диспелить можно с союзников :) Там флаг негативный в дбц

**Comment by Ramusik** [comment]
Ну этот баг вроде ж исправлен в spellmgr:

```
    case SPELLFAMILY_PRIEST:
        switch (spellId)
        {
            case 64844: // Divine Hymn
            case 64904: // Hymn of Hope
            case 47585: // Dispersion
                return true;
            default:
                break;
        }
```

Функция возвращает позитивные эффекты этих спелов

**Comment by tobmaps** [comment]
это неверный фикс. По крайней мере не помогает

**Comment by Ramusik** [comment]
Т.е. нужно просто убрать 

case 64844: // Divine Hymn
            spellInfo->AttributesEx &= ~SPELL_ATTR1_NEGATIVE;
            count++;
            break;

?

**Comment by tobmaps** [comment]
да

**Comment by tobmaps** [comment]
м, там не только в этом дело. Видать оба фикса нужны

В общем не убирая тот нужно применять ещё 

```
    case 64844: // Divine Hymn 
    case 64904: // Hymn of Hope
        spellInfo->AttributesEx &= ~SPELL_ATTR1_NEGATIVE;
        ++count;
        break;
```

ваш патч лучше так

```
    case SPELL_DAMAGE_CLASS_NONE:
        // We need more spells to find a general way (if there is any)
        switch (spellProto->Id)
        {
            case 379:   // Earth Shield
            case 33778: // Lifebloom Final Bloom
            case 64844: // Divine Hymn
                break;
            default:
                return false;
        }
```

**Comment by tobmaps** [comment]
в [p144]
