### ISSUE TITLE
[Death Grip] Not Flying

### ISSUE THREAD

**Issue by L30m4nc3r** [tobmaps/TrinityCore#48]
Взял за основу офф тринити.
Накатил все ваши патчи, tobmaps.
Теперь отказался работать вот этот спелл:
http://www.wowhead.com/spell=49576
http://www.wowhead.com/spell=49560#modified-by
Спелл жмется, появляется эта полоса от игрока к игроку, но увы он не притягивает.
Нечего не делает. В чем могла спрятаться проблема? Помогите пожалуйста решить.

**Comment by tobmaps** [comment]
Только что проверил, у меня притягивает. Вы через clone/pull ставили или же выборочно? Выборочно можно схлопотать багов =) У меня некоторые патчи зависят друг от друга

**Comment by tobmaps** [comment]
У вас наверно [p41] не обновленный стоит

**Comment by L30m4nc3r** [comment]
Спасибо большое:) Действительно руками накатывал и проморгал :) благодарю _DRINK_
