### ISSUE TITLE
Ауры питомцев после сброса талантов

### ISSUE THREAD

**Issue by Ramusik** [tobmaps/TrinityCore#51]
Вобщем есть баг - если взять талант http://db.uawow.com/?spell=35693, сбросить таланты / сменить спеку, то пет исчезает, но если засуммонить его заного - то аура таланта остается. Возможно есть подобные баги для других талантов и классов. 

Нашел решение перед удалением пета снимать с него все ауры. 

Патч: http://paste2.org/p/1390837

**Comment by tobmaps** [comment]
Но ведь это неверное решение, не должны сниматься _все_ ауры. Они не для того сохраняются в БД чтобы их всегда снимать %)

**Comment by tobmaps** [comment]
Только что проверил с указанным вами талантом и импом - бага нет у меня, ауры небыло на призванном в другом спеке пете

**Comment by Ramusik** [comment]
Вобщем, как получается баг:
1. Вызываем пета (например импа):
2. Раскидываем таланты в демонолога до таланта http://db.uawow.com/?spell=35693
3. Сбрасываем талы у тренера
4. Вызываем заново импа
5. Видим баф от таланта на игроке

Только что проверил, использую ядро с твоего форка

**Comment by tobmaps** [comment]
ну при переключении спека и при его сбросе выполняется совершенно разный код, мб в этом дело

Вы можете попробовать перетянуть чутка кода из Player::ActivateSpec в то место где у нас сброс талов

**Comment by tobmaps** [comment]
есть результаты? Я могу сейчас заняться этой проблемой

**Comment by tobmaps** [comment]
Должно быть исправлено в [p162]. По крайней мере я больше не смог воспроизвести
