### ISSUE TITLE
[Арена] Сумеречное зрение

### ISSUE THREAD

**Issue by Ramusik** [tobmaps/TrinityCore#52]
http://db.uawow.com/?spell=34709. Имеет 2 бага:
1. Должно снимать эффекты Стелса и Крадущегося зверя
2. Должно быть дебафом.

Можно увидеть на видео http://www.youtube.com/watch?v=X1qFfRH8I4g&feature=related на 1:18

Фикс (автор - я):
http://paste2.org/p/1392001

**Comment by tobmaps** [comment]
Это видео показало что уже запущенный спелл таки может попасть в рогу который вошел в стелс, однако неможет попасть по роге который использовал [Исчезновение], интересно...
Для тех кто не понял о чем я - смотрите ролик с 2:15 до 2:25

**Comment by tobmaps** [comment]
В общем фикс [p56] с добавлением Santuary эффекта стелсам был неверен
Это похоже нужно править AI, мб где-нибудь в Creature::Update

**Comment by tobmaps** [comment]
56ой от метафизикла заменил на свой вариант, теперь упомянутого мною бага нет. Щас с вашим разберемся

**Comment by tobmaps** [comment]
В общем добавил в [p154]
