### ISSUE TITLE
[Spell] Ignite

### ISSUE THREAD

**Issue by pipposo** [tobmaps/TrinityCore#55]
http://www.trinitycore.org/t/trinitycore/ticket/1263

**Comment by pipposo** [comment]
can you closed, resolved, it's my problem. ^^

**Comment by Ramusik** [comment]
I think this part is bugged:
And Ignite DoT may not benefits from any damage boosts - like Fire Power talent (correct) or Playing with Fire talent (bugged) and Thadius polarity boosts (bugged)
