### ISSUE TITLE
[Spell/Hunter] Some Hunter Beast Mastery Spells

### ISSUE THREAD

**Issue by pipposo** [tobmaps/TrinityCore#56]
http://www.trinitycore.org/t/trinitycore/ticket/585
"Spiked Collar (Ferocity) and Shark Attack (Ferrocity), they don´t increase pet damage."

**Comment by tobmaps** [comment]
both works fine for me. Not installed [p66]?

**Comment by pipposo** [comment]
yes installed [p66], but Shark Attack  don't work

**Comment by tobmaps** [comment]
did you tried to re-summon pet?

**Comment by pipposo** [comment]
ok..done.
