### ISSUE TITLE
Арена

### ISSUE THREAD

**Issue by L30m4nc3r** [tobmaps/TrinityCore#59]
Когда-нибудь будут работать последнии новые арены патча WotLK?
Может пора ими заняться :)
со спасобностями tobmaps это вполне реально)

**Comment by tobmaps** [comment]
запустить то их можно, я у себя на Мангосе имел их в достаточно играбельном виде. Единственная проблема так это то, что не работают коллизии у ГО (можно простреливать и т.д.). Без этого играть можно, но не приятно

Я смотрю вот https://github.com/SilverIce/mangos чел как раз реализацией этого дела и занимается, что ж... подождем когда закончит.

**Comment by L30m4nc3r** [comment]
Думаю это будет не скоро :)

**Comment by L30m4nc3r** [comment]
а вот у меня еще такое дело:
Перестала работать вот эта арена:
http://www.wowhead.com/zone=3702/blades-edge-arena
Вот в последние 2 месяца на неё не вызывает.
Поставил FUN реалм, точ точ тоже самое ядро. Вызывает, может с базой где беда? Подскажите пожалуйста?

Вот дамп battleground_template
http://pastebin.com/Ej7yq6qu
