### ISSUE TITLE
[pets stats] - doubt

### ISSUE THREAD

**Issue by Jildor** [tobmaps/TrinityCore#6]
Already work properly with your patches?, not crash?

**Comment by tobmaps** [comment]
i can't understand what are you mean under [pet stats]. You wanna to install my "pet" branch or what? If yes, that I don't know if it can crash or no, i don't have enough online to test it for stability, but some users from trinity-core.ru said that it works stable with online 200-250

**Comment by Jildor** [comment]
Yes sorry, I read that crashed, so I certainly wanted to know if it was good thing.

thx

**Comment by tobmaps** [comment]
anyway it has couple of own bugs like not scaling pets Shadowfiend, Inferno and maybe more. Also make some performance impact

**Comment by Jildor** [comment]
oks, then it is not currently recommended.

thx

**Comment by pipposo** [comment]
tobmaps thanks for the work you do

**Comment by tobmaps** [comment]
there is no useful info in this report, so closed
