### ISSUE TITLE
Pennance

### ISSUE THREAD

**Issue by Wattiqelumes** [tobmaps/TrinityCore#60]
Seems to sometimes give a 4th tick. Maybe lower the channel time?

Oh, I just heard it only gives a fourth tick if you use Borrowed Time.

**Comment by tobmaps** [comment]
can't reproduce. Did you try [p118]?

**Comment by Wattiqelumes** [comment]
Sorry, could you please link p118? I don't really understand what exactly you mean with these [p--] things. =P

**Comment by tobmaps** [comment]
better for you to watch repo changes through TortoiseGit - there exists a search by commit description, so you can find any patch
