### ISSUE TITLE
Bladestorm

### ISSUE THREAD

**Issue by Wattiqelumes** [tobmaps/TrinityCore#61]
Bladestorm still seems not to be immune to knock-back effects. Tested with Blastwave.

**Comment by tobmaps** [comment]
It shouldn't give "immune" vs Blastwave - it just doesn't push you from mage, but the damage is dealed. This one works fine for me (with [p67]). Closing

**Comment by Wattiqelumes** [comment]
Strange, for me it also knocks back the warrior. o_O

**Comment by tobmaps** [comment]
it only means that your not installed [p67]

**Comment by kbinside** [comment]
can you put this to official repo?

**Comment by tobmaps** [comment]
this patch is a hack

**Comment by kbinside** [comment]
hack?

**Comment by tobmaps** [comment]
hack = bad solution :) It may work fine but solution isn't good

**Comment by kbinside** [comment]
i don't get it :D why it should stay not fixed (yeah i know it is fixed) but why not to add?

**Comment by Wattiqelumes** [comment]
Because it's not properly fixed. Jesus, go do some research mate.

**Comment by kbinside** [comment]
i do every day
