### ISSUE TITLE
[Stun] Iron Will, Hardiness & Meta Gem

### ISSUE THREAD

**Issue by Wattiqelumes** [tobmaps/TrinityCore#62]
Iron Will talent stacks with the orc racial Hardiness and the meta gem which reduces stuns by 45%,all of those shouldn't stack.

**Comment by tobmaps** [comment]
meta fixed in [p169] already, racial and talents should stack as i know

**Comment by Wattiqelumes** [comment]
This is a straight copy from someone's post on my forums:

"Actually they should stack, but not the way you said. They don't stack like 15%+20%+10% = 45% reduction, no they stack multiplicatively. For an example lets take 5 CP Kidney Shot which is a 6 second stun without reductions.

1) So first the stun gets reduced by Hardiness which is a 15% reduction, so -> 6 sec \* 0.85 = 5.1 sec.
2) Next the 5.1 sec left gets reduced by Iron Will which is a 20% reduction -> 5.1 sec \* 0.8 = 4.08 sec.
3) And last the stun gets reduced by the meta gem which is a 10% reduction -> 4.08 sec \* 0.9 = 3.7 sec.

So in total that's a 38% stun reduction. Correct me if I'm wrong. :p"
