### ISSUE TITLE
Mocking Blow

### ISSUE THREAD

**Issue by Wattiqelumes** [tobmaps/TrinityCore#63]
Warrior's protection talent Mocking Blow should not do damage to players.

**Comment by tobmaps** [comment]
and it doesn't, fixed for a long time ago by [p41]

**Comment by Wattiqelumes** [comment]
Apply it on official repo, please. =)

**Comment by tobmaps** [comment]
can't, it's a hack as i think

**Comment by Wattiqelumes** [comment]
can you link it please? :D (would spare me hours finding it)

**Comment by tobmaps** [comment]
use TortoiseGIT
