### ISSUE TITLE
Art of War

### ISSUE THREAD

**Issue by Wattiqelumes** [tobmaps/TrinityCore#64]
Judgement crits also trigger Art of War. This shouldn't be!

**Comment by tobmaps** [comment]
Judgement is counted as melee ability (just has more range than other abilities). Where you get your info that it shouldn't?

if you will find any good confirmations than i will add this

```
UPDATE `spell_proc_Event` SET `SpellFamilyMask0` = 0 WHERE `entry` IN (53486,53488);
```

**Comment by Wattiqelumes** [comment]
Was incorrect, sorry.
Closing!
