### ISSUE TITLE
Master Poisoner

### ISSUE THREAD

**Issue by Wattiqelumes** [tobmaps/TrinityCore#67]
Also reduces the time of your OWN Envenom. ;)

**Comment by tobmaps** [comment]
i also can add that Envenom can be dispelled from you. Seems because it's negative spell that applies some effects at your own

**Comment by Wattiqelumes** [comment]
Can't confirm that. Sorry.

**Comment by Ramusik** [comment]
try - http://paste2.org/p/1403982

**Comment by tobmaps** [comment]
fixed both bugs in alternative way in [p179]
