### ISSUE TITLE
Slice and Dice

### ISSUE THREAD

**Issue by Wattiqelumes** [tobmaps/TrinityCore#68]
Puts you in combat for some reason.

**Comment by tobmaps** [comment]
it's because first effect of this spell have

```
Targets (6, 0) (TARGET_UNIT_TARGET_ENEMY, NO_TARGET)
```

this type of target is always negative. Need to overwrite it by hack...

**Comment by Wattiqelumes** [comment]
Off you go, I guess?! :D

**Comment by tobmaps** [comment]
fixed in [p180]
