### ISSUE TITLE
Spell Steal

### ISSUE THREAD

**Issue by Wattiqelumes** [tobmaps/TrinityCore#72]
Takes away all stacks of Earth/Water/Elemental Shield (shaman) in once.

**Comment by tobmaps** [comment]
known problem with stealing Earth Shield, all other shields should be stealed in one cast - because they doesn't have SPELL_ATTR7_DISPEL_CHARGES, only Earth Shield has

**Comment by Wattiqelumes** [comment]
Oh. Okay! :)

**Comment by tobmaps** [comment]
Fixed in official repo
