### ISSUE TITLE
Duel

### ISSUE THREAD

**Issue by Wattiqelumes** [tobmaps/TrinityCore#83]
Whenever you win a duel, you are not getting the /cheer effect.

PS. I am not sure if this effect was removed, but if not I'd love to get this put in. :)

**Comment by tobmaps** [comment]
it's not so hard to fix, but at least need some confirmations from official

**Comment by Ramusik** [comment]
http://www.youtube.com/watch?v=sMTYIsIhx8E&feature=related

**Comment by Ramusik** [comment]
http://www.youtube.com/watch?v=T_Qmf3m1LyY кароч на обеих видео победитель в конце поднимает руку вверх

**Comment by Wattiqelumes** [comment]
That's from 3.0.9, but it should still be on 3.3.5a.

**Comment by tobmaps** [comment]
we need to use HandleEmoteCommand(EMOTE_ONESHOT_CHEER); somewhere in duel code, i just haven't time to find where to place it

**Comment by Retriman** [comment]
tobmaps, add in void Player::DuelComplete(DuelCompleteType type), in player.cpp  line 7504 :)

**Comment by tobmaps** [comment]
I've tested this feature at Cataclysm and what i see - it's happen only when you getting achievement http://www.wowhead.com/achievement=1157

**Comment by tobmaps** [comment]
okay, tested again AT OFFICIAL and it really makes this emotion at every win. I don't know what it been before :/ Maybe bug for undeads when moving, my new orc playing this emote without problems for every win

**Comment by Wattiqelumes** [comment]
Incredible why you're saying that. It does not work at all!!

**Comment by tobmaps** [comment]
fixed in main repo
