### ISSUE TITLE
City Defender

### ISSUE THREAD

**Issue by Wattiqelumes** [tobmaps/TrinityCore#84]
Completely bugged. You get it from jumping down a cliff.

**Comment by tobmaps** [comment]
from what place you jump?

**Comment by Wattiqelumes** [comment]
Tested in Thunderbluff.

**Comment by tobmaps** [comment]
funny bug :) So easy to reproduce... seems something wrong in core part. Can you try this http://paste2.org/p/1404157 . Maybe it can broke some suicidal achievements, but should solve this one - at least you will not know without test :S

**Comment by tobmaps** [comment]
Fixed in official repo
