### ISSUE TITLE
Summon Water Elemental

### ISSUE THREAD

**Issue by Wattiqelumes** [tobmaps/TrinityCore#88]
If your Water Elemental died and you re-summon it shortly after, it spawns death.

**Comment by tobmaps** [comment]
i doesn't spawns as dead, It's just laying dead at the ground for some time and when you trying to summon new one it just activate cooldown at spell bud does nothing (pet already exists, even if this a dead pet) - i don't know how it should work, maybe pet should just disappear if killed or this dead pet should disappear if you trying to summon new one :/ need more info

**Comment by Wattiqelumes** [comment]
I've played a mage on retail and I can tell you this:
If a Water Elemental gets killed, it disappears.
If you summon a NEW one whilst it was killed a short time before you summon your new one, it should 'revive' and fight again. Right now if the time between dieing and summoning is too short, it spawns death.

**Comment by tobmaps** [comment]
```
Right now if the time between dieing and summoning is too short, it spawns death.
```

it doesn't spawns as dead for me, you can't summon new one until corpse of previous will disappear

**Comment by Wattiqelumes** [comment]
Strange, my comment got removed.

I wrote that I made a mistake. I meant that when your previous one died, the body stays and you can't summon a new one.
Also figured out pet cooldowns don't reset when you summon a new one.

**Comment by tobmaps** [comment]
i think pets shouldn't reset cooldowns of their spells because it can be abused, for example by warlocks - they will just do resummon to use abilities with 2 min cooldown. Need confirmations

**Comment by Wattiqelumes** [comment]
Not all pets, only counts for mage. ;)

**Comment by tobmaps** [comment]
Fixed in [p192]
