### ISSUE TITLE
Ice Block / Forbearance

### ISSUE THREAD

**Issue by Wattiqelumes** [tobmaps/TrinityCore#90]
Forbearance also affect Ice Block. If the mage has Forbearance on him, he can no longer cast Ice Block. (Hand of Protection also gives Forbearance)

**Comment by tobmaps** [comment]
need to get official info, or at least comments from some sites

**Comment by Wattiqelumes** [comment]
There is NO way Ice Block should be connected to Forbearance. Just not logical, at all.

**Comment by tobmaps** [comment]
after reading some sites now i can confirm your info, need to research some code...

**Comment by Wattiqelumes** [comment]
I'm happy about that :D

**Comment by Wattiqelumes** [comment]
Fixed in official, thanks tobmaps.
