### ISSUE TITLE
Rapid Recuperation

### ISSUE THREAD

**Issue by Wattiqelumes** [tobmaps/TrinityCore#94]
It returns the correct mana value under the effect of Rapid Fire, but it doesn't return any mana under the effect of Rapid Killing.
WOTLK spell:
[You gain 4% of your mana every 3 sec while under the effect of Rapid Fire, and you gain 2% of your mana every 2 sec for 6 sec when you gain Rapid Killing]

**Comment by tobmaps** [comment]
already fixed in [p63]
