### ISSUE TITLE
Можно ли?

### ISSUE THREAD

**Issue by L30m4nc3r** [tobmaps/TrinityCore#95]
Возможно ли, http://wowdata.ru/spell.html?id=698
Отключить возможность ставить ШКАФ, на бг.
или-же сделать проверку как вот тут на все действующие БГ.
http://pastebin.com/DC2V7JPr

**Comment by tobmaps** [comment]
ну вообще это могли бы вы и сами сделать через disables, не так уж и сложно...
Но решил все же пойти более грамотным путем, исправлено в [p185]
